# Automatically generated by configure, do not edit
PREFIX=/home/pivos/xbmc-depends/arm-linux-androideabi-android-17
libdir=${exec_prefix}/lib
shlibdir=/home/pivos/xbmc-depends/arm-linux-androideabi-android-17/lib
incdir=/home/pivos/xbmc-depends/arm-linux-androideabi-android-17/include/dvdnav
THREADLIB=-lpthread
BUILD_SHARED=no
BUILD_STATIC=yes
SHLIB_VERSION=4.2.1
SHLIB_MAJOR=4
CC=/opt/arm-linux-androideabi-4.8-vanilla/android-17/bin/arm-linux-androideabi-gcc
MAKE=make
CFLAGS=-O3  -O2 -g -D_DEBUG -Wall -DANDROID -Os -fexceptions -march=armv7-a -mtune=cortex-a9 -mfloat-abi=softfp -mfpu=neon -I/home/pivos/xbmc-depends/arm-linux-androideabi-android-17/include/android-17 -isystem /home/pivos/xbmc-depends/arm-linux-androideabi-android-17/include -DANDROID -Os -fexceptions -march=armv7-a -mtune=cortex-a9 -mfloat-abi=softfp -mfpu=neon -I/home/pivos/xbmc-depends/arm-linux-androideabi-android-17/include/android-17 -isystem /home/pivos/xbmc-depends/arm-linux-androideabi-android-17/include -O3 -fPIC -DPIC -D_REENTRANT -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -Wno-psabi -mno-apcs-stack-check -mfpu=neon -mvectorize-with-neon-quad -D_XBMC -DHAVE_DVDCSS_DVDCSS_H -I/home/pivos/proj/xbmc-16.1-Jarvis/lib/libdvd/libdvdnav/../includes -D_FILE_OFFSET_BITS=64 -D_OFF_T_DEFINED_ -Doff_t=off64_t -Dlseek=lseek64
LDFLAGS= -L/home/pivos/proj/xbmc-16.1-Jarvis/lib/libdvd/libdvdnav/../libdvdread/obj
SHLDFLAGS=-shared
INSTALLSTRIP=-s
USEDEBUG=-g
DVDREAD_CFLAGS=
DVDREAD_LIBS=-ldvdread

SRC_PATH="/home/pivos/proj/xbmc-16.1-Jarvis/lib/libdvd/libdvdnav"
SRC_PATH_BARE=/home/pivos/proj/xbmc-16.1-Jarvis/lib/libdvd/libdvdnav

