SRCS  = CDDARipJob.cpp
SRCS += CDDARipper.cpp
SRCS += Encoder.cpp
SRCS += EncoderFFmpeg.cpp

LIB=cdrip.a

include /home/pivos/proj/xbmc-16.1-Jarvis/Makefile.include
-include $(patsubst %.cpp,%.P,$(patsubst %.c,%.P,$(SRCS)))
