SET(APP_NAME Kodi)
SET(APP_NAME_LC kodi)
SET(APP_NAME_UC KODI)
SET(APP_VERSION_MAJOR 16)
SET(APP_VERSION_MINOR 1)
IF(NOT KODI_PREFIX)
  SET(KODI_PREFIX /home/pivos/xbmc-depends/arm-linux-androideabi-android-17)
ENDIF()
IF(NOT KODI_INCLUDE_DIR)
  SET(KODI_INCLUDE_DIR /home/pivos/xbmc-depends/arm-linux-androideabi-android-17/include/kodi)
ENDIF()
IF(NOT KODI_LIB_DIR)
  SET(KODI_LIB_DIR /home/pivos/xbmc-depends/arm-linux-androideabi-android-17/lib/kodi)
ENDIF()
IF(NOT WIN32)
  SET(CMAKE_CXX_FLAGS "$ENV{CXXFLAGS} ")
ENDIF()
LIST(APPEND CMAKE_MODULE_PATH /home/pivos/xbmc-depends/arm-linux-androideabi-android-17/lib/kodi)
ADD_DEFINITIONS(-DTARGET_POSIX -DTARGET_LINUX -D_LINUX -DTARGET_ANDROID -DBUILD_KODI_ADDON)

if(NOT CORE_SYSTEM_NAME)
  if(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
    set(CORE_SYSTEM_NAME "osx")
  else()
    string(TOLOWER ${CMAKE_SYSTEM_NAME} CORE_SYSTEM_NAME)
  endif()
endif()

include(addon-helpers)
