SRCS = DummyVideoPlayer.cpp
SRCS += FFmpeg.cpp
SRCS += DataCacheCore.cpp

LIB = cores.a

include /home/pivos/proj/xbmc-16.1-Jarvis/Makefile.include
-include $(patsubst %.cpp,%.P,$(patsubst %.c,%.P,$(SRCS)))
