SRCS  = PlayerCoreFactory.cpp
SRCS += PlayerSelectionRule.cpp

LIB = playercorefactory.a

include /home/pivos/proj/xbmc-16.1-Jarvis/Makefile.include
-include $(patsubst %.cpp,%.P,$(patsubst %.c,%.P,$(SRCS)))

